name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Code Check
        run: yarn lint

      - name: Test
        run: pnpm test:coverage
        env:
          ZOTERO_AUTH_KEY: ${{ secrets.ZOTERO_AUTH_KEY }}

      - uses: codecov/codecov-action@v1
