name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - uses: c-hive/gha-yarn-cache@v1

      - name: install
        run: yarn

      - name: Code Check
        run: yarn lint

      - name: Test
        run: yarn test:coverage
        env:
          ZOTERO_AUTH_KEY: ${{ secrets.ZOTERO_AUTH_KEY }}

      - uses: codecov/codecov-action@v1
